apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-friends-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: 页面标题
          name: title
          validation: required
          value: '友链朋友圈'
        - $formkit: text
          label: 朋友圈列表显示条数
          name: pageSize
          validation: required|Number
          value: 10
        - $formkit: select
          name: disableSynchronizationList
          label: 禁止同步名单
          multiple: true
          clearable: true
          searchable: true
          action: /apis/api.plugin.halo.run/v1alpha1/plugins/PluginLinks/links
          requestOption:
            method: GET
            pageField: page
            sizeField: size
            totalField: total
            itemsField: items
            labelField: spec.displayName
            valueField: metadata.name
